### ISSUE TITLE
Unable to download FCL data

### ISSUE THREAD

**Issue by mojesty** [UniversalDependencies/UD_English-ESL#1]
While clicking on [this link](https://ilexir.co.uk/applications/clc-fce-dataset/) i have just a blank page with the following text:
`<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>F25D5ECBD269A1D7</RequestId><HostId>dSM9T3Vk5ZXatUhP07KN1Fn9VJKDxslboTzvV0WVb9y35St0q2cTgwOH0RF6uhMpqicoXTi18B0=</HostId></Error>`
Is there any way to fix this problem?

**Comment by berzak** [comment]
Thanks for letting us know. The FCE page is currently here: 
https://www.ilexir.co.uk/datasets/index.html
