### ISSUE TITLE
How do I use en_esl-ud-*.conllu

### ISSUE THREAD

**Issue by JyiHUO** [UniversalDependencies/UD_English-ESL#3]
I open the file `en_esl-ud-dev.conllu` I found that:

![image](https://user-images.githubusercontent.com/16526817/50267674-01cd0e80-0463-11e9-9ecc-778358008910.png)

After I open the file and its name equal sent_id:

![image](https://user-images.githubusercontent.com/16526817/50267757-46f14080-0463-11e9-8556-c7b15aa23e26.png)

So, my question is how do I interpret them?

**Comment by berzak** [comment]
please run merge.py (with python 2) to obtain the underlying text.
