### ISSUE TITLE
Unable to download treebank with text by merge.py

### ISSUE THREAD

**Issue by WangYuxuan93** [UniversalDependencies/UD_English-ESL#4]
I have downloaded and unzipped the 'fce-released-dataset' following the instructions in README.
But when I ran the merge.py it reported "Error: Failed obtaining annotations with data from the specified url".
I have checked the script and found that it tries to download the 'data.zip' from the url 'http://esltreebank.org/data-2.3-1711/data.zip' but failed.
Could anyone help me ?
Has the link been changed ?

**Comment by berzak** [comment]
The server was down. You should be able to obtain the data now (please run the merge script with python 2).
